### ISSUE TITLE
fetch error

### ISSUE THREAD

**Issue by kingmxiii** [phpv8/v8js#268]
When I try to execute fetch v8 on centos 6 i get the following error

[root@vtigertest tmp]# fetch v8
Running: gclient root
Traceback (most recent call last):
  File "/tmp/depot_tools/fetch.py", line 300, in <module>
    sys.exit(main())
  File "/tmp/depot_tools/fetch.py", line 295, in main
    return run(options, spec, root)
  File "/tmp/depot_tools/fetch.py", line 281, in run
    if not options.force and checkout.exists():
  File "/tmp/depot_tools/fetch.py", line 80, in exists
    gclient_root = self.run_gclient('root').strip()
  File "/tmp/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, *_kwargs)
  File "/tmp/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, *_kwargs)
AttributeError: 'module' object has no attribute 'check_output'
[root@vtigertest tmp]#

**Comment by stesie** [comment]
This is an issue with V8's (or Google's) Depot tools. Yet my wild guess would be that your python version is too old.
